"""update table

Revision ID: c3078413f209
Revises: 
Create Date: 2026-03-02 12:12:40.315115
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'c3078413f209'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
